package main

var SupportedTypes = []SupportedType{
	SupportedType{
		TypeName:      "Method",
		TitleSuffix:   "Methods",
		AppendParents: true,
		IsContainer:   true,
		ShowNamespace: true,
	},
	SupportedType{
		TypeName:      "Constructor",
		TitleSuffix:   "Constructors",
		AppendParents: true,
		IsContainer:   true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Class",
		TitleSuffix:   "Class",
		PushName:      true,
		AppendParents: true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Namespace",
		TitleSuffix:   "Namespace",
		PushName:      true,
		AppendParents: true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Interface",
		TitleSuffix:   "Interface",
		PushName:      true,
		AppendParents: true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Statement",
		ID:            "langCon_apex_SOQL_query_all_rows",
		TitleOverride: "ALL ROWS",
	},
	SupportedType{
		TypeName:      "Statement",
		TitleSuffix:   "Statement",
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Enum",
		TitleSuffix:   "Enum",
		AppendParents: true,
		ShowNamespace: true,
	},
	SupportedType{
		TypeName:      "Property",
		TitleSuffix:   "Properties",
		AppendParents: true,
		IsContainer:   true,
		ShowNamespace: true,
	},
	SupportedType{
		TypeName:      "Guide",
		TitleSuffix:   "Example Implementation",
		NoTrim:        true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Statement",
		TitleSuffix:   "Statements",
		NoTrim:        true,
		AppendParents: false,
		IsContainer:   true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Field",
		TitleSuffix:   "Fields",
		AppendParents: true,
		PushName:      true,
		IsContainer:   true,
		ShowNamespace: true,
	},
	SupportedType{
		TypeName:      "Exception",
		TitleSuffix:   "Exceptions",
		NoTrim:        true,
		AppendParents: true,
		ShowNamespace: false,
		ParseContent:  true,
	},
	SupportedType{
		TypeName:      "Constant",
		TitleSuffix:   "Constants",
		NoTrim:        true,
		AppendParents: true,
		ShowNamespace: false,
		ParseContent:  true,
	},
	SupportedType{
		TypeName:      "Class",
		TitleSuffix:   "Class (Base Email Methods)",
		PushName:      true,
		AppendParents: true,
		ShowNamespace: false,
	},
	SupportedType{
		TypeName:      "Guide",
		TitlePrefix:   "Best Practices",
		TitleSuffix:   "Best Practices",
		NoTrim:        true,
		PushName:      false,
		AppendParents: false,
		ShowNamespace: false,
	},
	SupportedType{
		IDPrefix: "pages_compref_",
		TypeName: "Tag",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_maps",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_dynamic_vf",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_comp_cust",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_resources",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_controller",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_styling",
		NoTrim:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_security",
		NoTrim:   true,
	},
	SupportedType{
		TypeName:      "Variables",
		TitleSuffix:   "Global Variables",
		NoTrim:        true,
		AppendParents: true,
		ShowNamespace: false,
		ParseContent:  true,
		IsContainer:   true,
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_variables_functions",
	},
	SupportedType{
		TypeName: "Guide",
		IDPrefix: "pages_variables_operators",
	},
	SupportedType{
		TypeName:    "Guide",
		ID:          "apex_intro_get_started",
		CascadeType: true,
	},
}
